---
- hosts: your_ubuntu_servers
  become: true  # Run tasks with sudo

  tasks:
    - name: Install aptitude package manager (if not already installed)
      apt:
        name: aptitude
        state: present

    - name: Add Grafana APT repository key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana APT repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana

    - name: Update APT and install Grafana
      apt:
        name: grafana
        state: latest

    - name: Start Grafana service and enable it on boot
      systemd:
        name: grafana-server
        state: started
        enabled: yes
